version: "3.9"
services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3080:3080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
